version: "3.8"

services:
  app:
    build: ./app
    container_name: app
    volumes:
      - /app/node_modules/
    ports:
      - 8080:8080

  server:
    build: ./server
    container_name: server
    ports:
      - 5000:5000